<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('zeomatics inc.'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('zero') ?>"><?php echo sprintf($this->translate('%szeomatics Inc.%s'), '<span class="page_color">', '</span>') ?></a>
                    <!--<a class="navbar-brand" href="<?php // echo $this->url('home') ?>"><img src="<?php // echo $this->basePath('img/zeomatics-logo.png') ?>" alt=""/>&nbsp;<?php // echo $this->translate('zeomatics Inc.') ?></a>-->
                </div>
                <div id="nav-menu">
                    <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('Navigation')->menu()->setUlClass('nav navbar-nav'); ?>
                    </div>
                    <!--<div class="collapse navbar-collapse">
                        <?php // <-- Update this !!
                    //    echo $this->navigation('navigation')
                    //              ->menu()
                    //              ->setMinDepth(0)
                    //              ->setMaxDepth(0)
                    //              ->setUlClass('nav navbar-nav');
                        ?>
                    </div>-->
                </div>
            </div>
        </nav>
        <div class="container-fluid" id="body-container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        
        <div class="container-fluid">
            <div class="graybackground" id="footer-container">
                <div class="row">
                    <div class="col-xs-10 col-xs-offset-1">
                        <div class="col-md-4 col-xs-12">
                            <div class="widget">
                                <h3 class="widget-title">About Us</h3>
                                <p >We're passionate just like you. Together we can transform our world.</p>
                                <a class="btn btn-success btn-lg page_background" href="zero/about/">Learn More  <span class="glyphicon glyphicon-play"></span></i></a>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-12">
                            <div class="widget">
                                <h3 class="widget-title ">We offer</h3>
                                <p>Project consulting, implementation services, knowledge transfer and delivery of ready-to-use systems.</p>
                                <a class="btn btn-success btn-lg page_background" href="zero/consulting/">See Our Work  <span class="glyphicon glyphicon-play"></span></a>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-12">
                          <div class="widget">
                            <h3 class="widget-title ">Connect</h3>
                            <p style="margin-bottom: 15px;" >We’d love to hear from you. Come see us in New Delhi or email us at <a id="mail" class="page_color" href="mailto: connect@zeomatics.com">connect@zeomatics.com</a></p>
<!--                            <p style="margin-bottom: 25px; font-size: 16px;" >
                              Phone number
                            </p>-->
                            <div class="social-links">
                                <a class="page_color" target="_blank" href="http://www.twitter.com/zeomatics" onclick="_gaq.push(['_trackEvent', 'Footer', 'Twitter Social Link', 'Click']);"><img src="<?php echo $this->basePath('img/widget-icons/Twitter.png'); ?>" width=30px;> Twitter</a>
                                <a class="page_color" target="_blank" href="http://www.linkedin.com/company/zeomatics" onclick="_gaq.push(['_trackEvent', 'Footer', 'LinkedIn Social Link', 'Click']);"><img src="<?php echo $this->basePath('img/widget-icons/LinkedIn.png'); ?>" width=30px;> LinkedIn</a>
                                <a class="page_color" target="_blank" href="http://www.facebook.com/zeomatics" onclick="_gaq.push(['_trackEvent', 'Footer', 'LinkedIn Social Link', 'Click']);"><img src="<?php echo $this->basePath('img/widget-icons/Facebook.png'); ?>" width=30px;> Facebook</a>
                            </div> 
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <footer>
            <!--<div class="widget-area">-->
                <div class="container">
                    <p>&copy; <?php echo date('Y') ?> by Zeomatics Inc. <?php echo $this->translate('All rights reserved.') ?></p>
                </div>
            <!--</div>-->
        </footer>
        <?php echo $this->inlineScript() ?>
        <script>
            //For shrinking the menu bar on scroll along with the bottom border of navbar
//            $(window).scroll(function() {
//              if ($(document).scrollTop() > 414) {
//                $('nav').addClass('shrink');
//                $('.navbar-fixed-top .container').css( "border-bottom", "1px" );
//              } else {
//                $('nav').removeClass('shrink');
//                $('.navbar-fixed-top .container').css( "border-bottom", "" );
//              }
//            });
            $(document).ready(function(){
                $(window).scroll(function() {
                    var check = $('#menu-shrink-mark').position();
                    if ($(document).scrollTop() > check.top-90) {
                            $('nav').addClass('shrink');
                            $('.navbar-fixed-top .container').css( "border-bottom", "1px" );
                          } else {
                            $('nav').removeClass('shrink');
                            $('.navbar-fixed-top .container').css( "border-bottom", "" );
                          }
                });
            });
        </script>
    </body>
</html>
