<br/>
<br/>
<br/>
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <h1 class="section-title"><?php echo $this->translate('404 error') ?></h1>
        <div class="jumbotext3">
            <img src="<?php echo $this->basePath('img/puzzled-smiley-emoticon.gif');?>" />
            <?php // echo sprintf($this->translate('%sOops!%s I think i lost it somewhere.'),'<span class="green">', '</span>') ?>
            <?php // echo sprintf($this->translate('%sOh my god!%s I am so embarassed. What do i do?'),'<span class="green">', '</span>') ?>
            <?php echo sprintf($this->translate('Ok...We\'ve %sgot a problem here%s. Let me think where it went wrong.'),'<span class="page_color">', '</span>') ?>
            <a class="btn btn-success btn-lg page_background" href="../zero">TAKE ME HOME <span class="glyphicon glyphicon-play"></span></a>
        </div>
    </div>
</div>
<br/>
<br/>
<br/>
