<br/>
<br/>
<br/>
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <h1 class="section-title"><?php echo $this->translate('404 error') ?></h1>
        <div class="jumbotext3">
            <img src="../img/puzzled-smiley-emoticon.gif">
            <?php // echo sprintf($this->translate('%sOops!%s I think i lost it somewhere.'),'<span class="green">', '</span>') ?>
            <?php // echo sprintf($this->translate('%sOh my god!%s I am so embarassed. What do i do?'),'<span class="green">', '</span>') ?>
            <?php echo sprintf($this->translate('Ok...We\'ve %sgot a problem here%s. Let me think where it went wrong.'),'<span class="green">', '</span>') ?>
            <a class="btn btn-success btn-lg" href="zero/contact/">TAKE ME HOME <i class="icon-btn" style="right: 18px;"></i></a>
        </div>
    </div>
</div>
<br/>
<br/>
<br/>