<!--<h1>Zeomatics Index Page</h1>-->

<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery.bxslider.css'));
?>
<style>
    .page_color{
        /*color: #00ebff;   //Light Blue*/
        /*color: #3cc197;   //*/
        color: green;
    }
    .page_background{
        background-color: green;
        color: #eee;
    }
</style>
<div class="darkbackground">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext">
                <?php // echo sprintf($this->translate('Great businesses are built on %sgreat experiences%s. We make those experiences happen.'), '<span class="green">', '</span>') ?>
                <?php echo sprintf($this->translate('Get solutions for your %stoughest geospatial%s challenges with our determined team.'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
            </div>
            <a id="go_down" class="skip-icon page_background" title="Skip to content" href="#content"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
    </div>
</div>
<div class="row" id="menu-shrink-mark">
    <ul class="bxslider">
        <li><img src="<?php echo $this->basePath('img/RenderData_resized.jpg');?>" /></li>
        <li><img src="<?php echo $this->basePath('img/auroraNZ_weir_960high.jpg');?>" /></li>
        <!--<li><img src="<?php echo $this->basePath('img/');?>" /></li>-->
    </ul>
</div>
<!--<div class="row">
    <img class="img-responsive" src="../img/Home_Carousel_1_new-1441x720.jpg">
</div>-->
<!--<div class="darkbackground">-->
<div class="row" id="content">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">about us</h2>
            <div class="jumbotext3">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php // echo sprintf($this->translate('The ability to visualize important issues on a map. We help in better decision making.')) ?>
                <?php echo sprintf($this->translate('zeomatics Inc. is a dynamic multi-faceted company which provides industry with a variety of solutions.')) ?>
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="">
                <div class="col-md-12">
                    <p>We provide solutions to build a more secure and sustainable future by encouraging a better understanding and appreciation of the world's cultural and ecological diversity. </p>
                    <p>zeomatics' mission is to provide the expertise and technology needed to research, design and produce high quality cartographic and interactive media and printed products for our public and private sectors, NGOs and government agencies, universities and non-profit partners worldwide.</p>
                    <p>zeomatics also provides participatory research and consultation services designed to support our project partners in meeting the needs associated with community-based land use, ecological knowledge and cultural heritage mapping and with capacity building related to co-management, sustainable development and geo-spatial and multimedia skills and technology transfer.</p>
                    <p>The zeomatics team members have a vast background in agriculture, oil and gas, surveying, GIS and remote sensing making zeomatics the complete package.The processing expertise possessed within zeomatics creates the ability to tackle a wide range of applications.</p>
                </div>
            </div>
        </div>
    </div>
	<br/>
<!--<img src="../img/GIS.jpg">-->
    
<!--</div>-->
<div class="whitebackground"><br/><br/>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">Our Team</h2>
            <div class="jumbotext3">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php echo sprintf($this->translate('The difference between success and failure is a great team. ')) ?>
                </p>
            </div>
        </div>
    </div>
    <div class="row" id="expertise_info">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Abhishek_Jain.jpg" alt="Mr. Abhishek Jain">
                        <p><span class="page_color font-24">Abhishek Jain </span><br> Job Title</p>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Abhishek_Sachan.jpg" alt="Mr. Abhishek Sachan">
                        <p><span class="page_color font-24">Abhishek Sachan</span><br> Job Title</p>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Avinash_Kumar.jpg" alt="Mr. Avinash Kumar">
                        <p><span class="page_color font-24">Avinash Kumar </span><br> Job Title</p>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Dr._Devanjan_Bhattacharya.jpg" alt="Dr. Devanjan Bhattacharya">
                        <p><span class="page_color font-24">Devanjan Bhattacharya </span><br> Job Title</p>
                    </div>
                </div>

                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Ravi_Kumar.jpg" alt="Mr. Ravi Kumar">
                        <p><span class="page_color font-24">Ravi Kumar</span><br> Job Title</p>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Santosh_Yadav.jpg" alt="Mr. Santosh Yadav">
                        <p><span class="page_color font-24">Santosh Yadav</span><br> Job Title</p>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Sarat_Chandra.jpg" alt="Mr. Sarat Chandra">
                        <p><span class="page_color font-24">Sarat Chandra</span><br> Job Title</p>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Saurabh_Vijay.jpg" alt="Mr. Saurabh Vijay">
                        <p><span class="page_color font-24">Saurabh Vijay</span><br> Job Title</p>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="member">
                        <img class="img-rounded img-responsive" src="../img/team/Mr._Siddhartha_Khare.jpg" alt="Mr. Siddhartha Khare">
                        <p><span class="page_color font-24">Siddhartha Khare</span><br> Job Title</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<div class="darkbackground"><br/>
    <div class="row" id="geospatial">
        <div class="col-xs-10 col-xs-offset-1">
            <p class="font-54"><?php echo sprintf($this->translate('Geospatial technologies for sustainable economic and social development')) ?>
                <a class="btn btn-success btn-lg page_background" href="zero/">a future guideline  <span class="glyphicon glyphicon-play"></span></a>
            </p>
        </div>
    </div>
<br/>
</div>-->
<!--<div class="row"><br/>
    <div class="col-xs-10 col-xs-offset-1">
        <h2 class="section-title">Careers</h2>
        <img class="img img-responsive" src="../img/GIS_Day_2014_Slider3-2_03.png" style="">
        <div class="jumbotext2">
            <p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>
            <p style="text-align: center; text-transform: uppercase; font-size: smaller;">
            <?php // echo sprintf($this->translate('Overcome the challenges of your business by applying new strategies.')) ?>
            <?php echo sprintf($this->translate('Give your work a solid foundation.')) ?>
            <a class="btn btn-success btn-lg page_background" href="zero/portfolio">See how we work  <span class="glyphicon glyphicon-play"></span></a>
            </p>
        </div>
    </div>
</div>
<div class="row mapping_adv">
    <div class="col-xs-10 col-xs-offset-1">
        <h2 class="section-title">Applicable everywhere</h2><br/>
        <h2 class="section-title">We've got something for everybody</h2><br/>
        <div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Transportation</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Public Safety</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Defense</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Business/Commercial</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Environmental Management</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Facilities Management</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Geodesign</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Government</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Health & Human Services</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Land Administration & Cadastre</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Map, Chart, and Data Production</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Natural Resources</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Utilities and Communications</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Spatial Data Infrastructure</p>
            </div>
        </div>
    </div>
</div>-->
<!--<br/>-->
<div class="page_background">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext3">
                <?php echo sprintf($this->translate('How might we help you?')) ?>
                <a class="btn btn-default btn-lg" href="zero/contact/">GET IN TOUCH  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //For sliding images in the head slider
    $(document).ready(function(){
        $('.bxslider').bxSlider({
//            auto: true,
//            autoControls: true
          });
    });
</script>
