<!--<h1>Zeomatics Index Page</h1>-->

<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery.bxslider.css'));
?>
<style>
    .page_color{
        color:green;
    }
    .page_background{
        background-color: green;
        color: #eee;
    }
</style>
<div class="darkbackground">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext">
                <?php // echo sprintf($this->translate('Great businesses are built on %sgreat experiences%s. We make those experiences happen.'), '<span class="green">', '</span>') ?>
                <?php echo sprintf($this->translate('The organization dedicated to provide %sworld class solutions%s to geospatial problems.'), '<span class="page_color">', '</span>') ?>
            </div>
            <a id="go_down" class="skip-icon page_background" title="Skip to content" href="#content"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
    </div>
</div>
<div class="row" id="menu-shrink-mark">
    <ul class="bxslider">
        <li><img src="<?php echo $this->basePath('img/pic1.jpg');?>" /></li>
        <li><img src="<?php echo $this->basePath('img/pic2.jpg');?>" /></li>
        <li><img src="<?php echo $this->basePath('img/pic3.jpg');?>" /></li>
    </ul>
</div>
<!--<div class="row">
    <img class="img-responsive" src="<?php echo $this->basePath('img/Home_Carousel_1_new-1441x720.jpg');?>">
</div>-->
<!--<div class="darkbackground">-->
<div class="row" id="content">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">SERVICES</h2>
            <div class="jumbotext2">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php // echo sprintf($this->translate('The ability to visualize important issues on a map. We help in better decision making.')) ?>
                <?php echo sprintf($this->translate('We provide the ability to visualize and analyze important issues on a map.')) ?>
                    <a id="down" class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/services')?>">See how we work  <span class="glyphicon glyphicon-play"></span></a>
                </p>
            </div>
        </div>
    </div>
    <div class="row mapping_adv">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">Experience the Power of Mapping in</h2><br/>
            <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-5 col-md-offset-1 col-sm-offset-1 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/agriculture-1-130px.png');?>"/>
                    <p>Agriculture</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/engineering-1-130px.png');?>"/>
                    <p>Engineering</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/inspections-1-130px.png');?>"/>
                    <p>Inspections</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/forestry-1-130px.png');?>"/>
                    <p>Forestry</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/oil-gas-1-130px.png');?>"/>
                    <p>Oil & Gas</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-5 col-md-offset-2 col-sm-offset-2 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/environmental-1-130px.png');?>"/>
                    <p>Environmental Monitoring</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/aerial-imagery-1-130px.png');?>"/>
                    <p>GIS & Mapping</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/image-processing-1-130px.png');?>"/>
                    <p>Image Processing</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/volumetrics-1-130px.png');?>"/>
                    <p>Mining</p>
                </div>
            </div>
<!--            <div class="font-24">
                <div class="col-md-6">
                    <p><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Cost Savings from Greater Efficiency</p>
                </div>
                <div class="col-md-6">
                    <p><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Better Decision Making</p>
                </div>
                <div class="col-md-6">
                    <p><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Improved Communication</p>
                </div>
                <div class="col-md-6">
                    <p><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Managing Geographically</p>
                </div>
                <div class="col-md-6">
                    <p><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Better Record Keeping</p>
                </div>
            </div>-->
        </div>
    </div>
	<br/>
<!--<img src="<?php echo $this->basePath('img/GIS.jpg');?>">-->
    
<!--</div>-->
<div class="whitebackground"><br/><br/>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">TECHNOLOGY</h2>
            <div class="jumbotext2">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php echo sprintf($this->translate('Why settle for good when you can have the best?')) ?>
                    <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/technology')?>">View Technology <span class="glyphicon glyphicon-play"></span></a>
                </p>
            </div>
        </div>
    </div>
    <div class="row" id="expertise_info">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">WE'RE EXPERTS IN</h2>
            <div class="col-xs-6 col-md-3">
                <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/Lotus_Temple2.jpg');?>" alt="services image 1">
                <p>Monitoring of Land Resources</p>
            </div>
            <div class="col-xs-6 col-md-3">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/saraswati-river.jpg');?>">
                    <p>Monitoring of Water Resources</p>
            </div>
            <div class="col-xs-6 col-md-3">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/tanjil.jpg');?>">
                    <p>Space based Land assessment</p>
            </div>
            <div class="col-xs-6 col-md-3">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/classification.jpg');?>">
                    <p>Space based Classification</p>
            </div>
        </div>
    </div>
</div>
<div class="graybackground"><br/>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">PORTFOLIO</h2>
            <div class="jumbotext2">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php // echo sprintf($this->translate('We\'re passionate just like you. Together we can transform our world.')) ?>
                <?php echo sprintf($this->translate('New Strategies for New Times.')) ?>
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/portfolio');?>">View our work <span class="glyphicon glyphicon-play"></span></a>
                </p>
            </div>
        </div>
    </div>
    <div class="row" id="experience_info">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">We've experience in </h2><br/>
            <div class="row font-24">
                <div class="col-md-3 col-sm-6 col-xs-12"><p>
                    Developing Decision Support Systems
                </p></div>
                <div class="col-md-3 col-sm-6 col-xs-12"><p>
                    Analyzing satellite data for various applications
                </p></div>
                <div class="col-md-3 col-sm-6 col-xs-12"><p>
                    Site selection and route planning
                </p></div>
                <div class="col-md-3 col-sm-6 col-xs-12"><p>
                    Facilities management
                </p></div>
            </div>
            <div class="row font-24">
                <div class="col-md-3 col-sm-6 col-xs-12"><p>
                    Market planning and analytics.
                </p></div>
            </div>
        </div>
    </div>
    <br/>
</div>
<div class="darkbackground"><br/>
    <div class="row" id="geospatial">
        <div class="col-xs-10 col-xs-offset-1">
            <p class="font-54"><?php echo sprintf($this->translate('Geospatial technologies for sustainable economic and social development')) ?>
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero');?>">a future guideline  <span class="glyphicon glyphicon-play"></span></a>
            </p>
        </div>
    </div>
<br/>
</div>
<div class="row"><br/>
    <div class="col-xs-10 col-xs-offset-1">
        <h2 class="section-title">Applications</h2>
        <img class="img img-responsive" src="<?php echo $this->basePath('img/GIS_Day_2014_Slider3-2_03.png');?>" style="">
        <div class="jumbotext2">
            <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
            <p style="text-align: center; text-transform: uppercase; font-size: smaller;">
            <?php // echo sprintf($this->translate('Overcome the challenges of your business by applying new strategies.')) ?>
            <?php echo sprintf($this->translate('Give your work a solid foundation.')) ?>
            <!--<a class="btn btn-success btn-lg page_background" href="zero/portfolio">See how we work  <span class="glyphicon glyphicon-play"></span></a>-->
            </p>
        </div>
    </div>
</div>
<div class="row mapping_adv">
    <div class="col-xs-10 col-xs-offset-1">
        <!--<h2 class="section-title">Applicable everywhere</h2><br/>-->
        <h2 class="section-title">We've got something for everybody</h2><br/>
        <div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Transportation</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Public Safety</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Defense</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Business/Commercial</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Environmental Management</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Facilities Management</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Geodesign</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Government</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Health & Human Services</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Land Administration & Cadastre</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Map, Chart, and Data Production</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Natural Resources</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Utilities and Communications</p>
            </div>
            <div class="col-md-6">
                <p  class="font-24"><span class="glyphicon glyphicon-circle-arrow-right page_color"></span>  Spatial Data Infrastructure</p>
            </div>
        </div>
    </div>
</div>
<br/>
<div class="page_background">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext3">
                <?php echo sprintf($this->translate('How might we help you?')) ?>
                <a class="btn btn-default btn-lg" href="<?php echo $this->basePath('zero/contact');?>">GET IN TOUCH  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //For sliding images in the head slider
    $(document).ready(function(){
        $('.bxslider').bxSlider({
//            auto: true,
//            autoControls: true
          });
    });
</script>
<!--For Google+ Search-->
<a href="https://plus.google.com/100525295591674298691" rel="publisher"></a>