<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery.bxslider.css'));
?>

<style>
    .page_color{
        /*color: #d93600;*/
        color: #0bf397;
    }
    .page_background{
        background-color: #0bf397;
        color: #333;
    }
</style>
<div class="darkbackground">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext">
                <?php echo sprintf($this->translate('We provide applications and solutions that are %spowerful%s, yet %seasy to maintain%s and enhance.'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
            </div>
            <a id="go_down" class="skip-icon page_background" title="Skip to content" href="#content"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
    </div>
</div>
<div class="row" id="menu-shrink-mark">
    <ul class="bxslider">
        <li><img src="../img/auroraNZ_weir_960high.jpg" /></li>
        <!--<li><img src="../img/RenderData_resized.jpg" /></li>-->
        <!--<li><img src="../img/pic1.jpg" /></li>-->
    </ul>
</div>
<div class="container" id="content">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="jumbotext3">
                    <!--We deliver perfection-->
                    Integrating zeomatics with....everything
                    <!--<small>Subheading</small>-->
                </h1>
<!--                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">One Column Portfolio</li>
                </ol>-->
            </div>
        </div>
        <!-- /.row -->

        <!-- Project One -->
        <div class="row">
            <div class="col-md-7">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover project_image" src="<?php echo $this->basePath('img/portfolio/DSS2_snapshot.jpg');?>" alt="Decision Support System">
                </a>
            </div>
            <div class="col-md-5">
                <h3 class="project_title font-24">Decision Support System</h3>
                <h4 class="project_subtitle font-20">For enhancing water productivity in rice-wheat cropping system</h4>
                <p>A DSS for Agro-Technology transfer in rice-wheat cropping system (DSSAT-RW) providing to-the-point information to agriculturists to help them improve water productivity in different scenarios in order to reduce the input cost.</p>
                <!--<p>Water Productivity Decision Support System  for use by the irrigation water manager.</p>-->
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/portfolio#dss');?>">View project  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Two -->
        <div class="row">
            <div class="col-md-7">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover project_image" src="<?php echo $this->basePath('img/portfolio/DSS1_snapshot.jpg');?>" alt="Decision Support System">
                </a>
            </div>
            <div class="col-md-5">
                <h3 class="project_title font-24">DSS for Saline Environment</h3>
                <h4 class="project_subtitle font-20">For enhancing crop productivity</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/portfolio#dss');?>">View project  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
        <!-- /.row -->
        <hr>
        <!-- Project Two -->
        <div class="row">
            <div class="col-md-7">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover project_image" src="<?php echo $this->basePath('img/portfolio/route_planning.jpg');?>" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3 class="project_title font-24">GIS based optimal route planning</h3>
                <h4 class="project_subtitle font-20">For gas pipeline route</h4>
                <p>Various datasets from different sources were used for analysis in Geographic Information System (GIS) for developing a path way for gas pipeline in IIT Roorkee campus.</p>
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/portfolio#dss');?>">View project  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>
        <!-- Project Two -->
        <div class="row">
            <div class="col-md-7">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover project_image" src="<?php echo $this->basePath('img/portfolio/healthcare.jpg');?>" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3 class="project_title font-24">GIS based facility planning</h3>
                <h4 class="project_subtitle font-20">For medical facilities in rural areas</h4>
                <p>In this project planning is done for locating the new PHSCs(Primary Health Sub Centers) in Laksar area. Health authorities have always aimed to provide health care for all residents using a fair access policy that is characterized as providing the right service at the right time in the right place.</p>
                <!--<p>To ensure better medical facility planning, it is important to have reliable and accurate health facilities measures so that true services shortage areas can be accurately identified and resources allocated to those needy areas to alleviate the problem.</p>-->
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/portfolio#dss');?>">View project  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
        <!-- /.row -->
        <hr>
        <!-- Project Two -->
        <div class="row">
            <div class="col-md-7">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover project_image" src="<?php echo $this->basePath('img/portfolio/school.png');?>" alt="Decision Support System">
                </a>
            </div>
            <div class="col-md-5">
                <h3 class="project_title font-24">School building planning</h3>
                <h4 class="project_subtitle font-20">Subheading</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/portfolio#dss');?>">View project  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
        <!-- /.row -->
        <hr>
        <!-- Project Two -->
        <div class="row">
            <div class="col-md-7">
                <a href="portfolio-item.html">
                    <!--<img class="img-responsive img-hover project_image" src="<?php echo $this->basePath('img/portfolio/');?>" alt="">-->
                    <img class="img-responsive img-hover project_image" src="http://placehold.it/700x300" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3 class="project_title font-24">Project Title</h3>
                <h4 class="project_subtitle font-20">Subheading</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
                <a class="btn btn-success btn-lg page_background" href="<?php echo $this->basePath('zero/portfolio#dss');?>">View project  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
        <!-- /.row -->
        <hr>

        <!-- Pagination -->
<!--        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>-->
        <!-- /.row -->

        <hr>
    </div>
    <!-- /.container -->

<div class="page_background">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext3">
                <?php echo sprintf($this->translate('How might we help you?')) ?>
                <a class="btn btn-default btn-lg" href="zero/contact/">GET IN TOUCH  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //For sliding images in the head slider
    $(document).ready(function(){
      $('.bxslider').bxSlider();
    });
</script>
