<!--<h1>Zeomatics Services Page</h1>-->

<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery.bxslider.css'));
?>
<style>
    .page_color{
        color: #f4d503;
    }
    .page_background{
        background-color: #f4d503;
        color: #333;
    }
</style>
<div class="darkbackground">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext">
                <?php // echo sprintf($this->translate('Great businesses are built on %sgreat experiences%s. We make those experiences happen.'), '<span class="green">', '</span>') ?>
                <?php echo sprintf($this->translate('We provide the ability to %svisualize%s and %sanalyze%s important issues on a map.'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
            </div>
            <a id="go_down" class="skip-icon page_background" title="Skip to content" href="#content"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
    </div>
</div>
<div class="row" id="menu-shrink-mark">
    <ul class="bxslider">
        <li><img src="../img/pic3.jpg" /></li>
        <li><img src="../img/pic2.jpg" /></li>
        <li><img src="../img/pic1.jpg" /></li>
    </ul>
</div>
<!--<div class="row">
    <img class="img-responsive" src="img/Home_Carousel_1_new-1441x720.jpg">
</div>-->
<!--<div class="darkbackground">-->
<div class="row" id="content">
        <div class="col-xs-10 col-xs-offset-1">
            <!--<h2 class="section-title">SERVICES</h2>-->
<!--            <div class="jumbotext2">
                <p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>
                <p>
                <?php // echo sprintf($this->translate('The ability to visualize important issues on a map. We help in better decision making.')) ?>
                <?php // echo sprintf($this->translate('We provide the ability to visualize and analyze your issues on a map.')) ?>
                <a class="btn btn-success btn-lg page_background" href="zero/services">See how we work  <span class="glyphicon glyphicon-play"></span></a>
                </p>
            </div>-->
        </div>
    </div>
    <div class="row mapping_adv">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">Experience the Power of Mapping in</h2><br/>
            <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-5 col-md-offset-1 col-sm-offset-1 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/agriculture-1-130px.png');?>"/>
                    <p>Agriculture</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/engineering-1-130px.png');?>"/>
                    <p>Engineering</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/inspections-1-130px.png');?>"/>
                    <p>Inspections</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/forestry-1-130px.png');?>"/>
                    <p>Forestry</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/oil-gas-1-130px.png');?>"/>
                    <p>Oil & Gas</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-5 col-md-offset-2 col-sm-offset-2 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/environmental-1-130px.png');?>"/>
                    <p>Environmental Monitoring</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/aerial-imagery-1-130px.png');?>"/>
                    <p>GIS & Mapping</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/image-processing-1-130px.png');?>"/>
                    <p>Image Processing</p>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-5 services">
                    <img class="img-responsive services_icons page_background" src="<?php echo $this->basePath('img/services_icons/volumetrics-1-130px.png');?>"/>
                    <p>Mining</p>
                </div>
            </div>
        </div>
    </div>
	<br/>
<!--<img src="img/GIS.jpg">-->
    
<!--</div>-->
<div class="whitebackground"><br/><br/>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
<!--            <h2 class="section-title">TECHNOLOGY</h2>-->
            <div class="jumbotext2">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php echo sprintf($this->translate('Geomatics helps you discover the world.')) ?>
                    <!--<a class="btn btn-success btn-lg page_background" href="zero/technology">View Technology <span class="glyphicon glyphicon-play"></span></a>-->
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h2 class="section-title">An intro to what we do</h2>
            <div class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/cartography.jpg');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24">Cartography / Map Design</p>
                    <p>The practice of creating maps or visual representations of a surface from above it is known as Cartography. Traditionally maps have always on paper, but since the introduction & wide spread use of GIS, cartography has evolved more into digital formats.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5 col-lg-push-7">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/GIS.jpg');?>">
                </div>
                <div class="col-lg-7 col-lg-pull-5">
                    <p class="services_title font-24">Geographic Information Systems (GIS)</p>
                    <p>GIS have become a rapidly growing field that allows people to solve & model real world situations by incorporating spatial and tabular data. GIS operates on many levels and has become an essential tool for most urban and resource planning and management organizations.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/RS.gif');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24">Remote Sensing</p>
                    <p>Remote sensing is the science of acquiring information about a surface without physically being in contact with it. The most common example of remote sensing is aerial photography however there are hundreds of  applications ranging from space-borne satellites to under-ground geophysical systems.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5 col-lg-push-7">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/LIDAR.jpg');?>">
                </div>
                <div class="col-lg-7 col-lg-pull-5">
                    <p class="services_title font-24">LIDAR</p>
                    <p>LIDAR uses high precision GPS with an Inertial Measurement Unit (IMU) to determine accurate surface locations. The resultant measurements consists of geographic locations that can be further processed to produce different spatial data products. We have worked in all aspects of LIDAR, from data acquisition (with both airborne and terrestrial scanners) to processing and product creation.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <br/>
            <br/>
            <br/>
        </div>
    </div>
</div>
<div class="page_background">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext3">
                <?php echo sprintf($this->translate('How might we help you?')) ?>
                <a class="btn btn-default btn-lg" href="<?php echo $this->basePath('zero/contact');?>">GET IN TOUCH  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //For sliding images in the head slider
    $(document).ready(function(){
        $('.bxslider').bxSlider({
//            auto: true,
//            autoControls: true
          });
    });
</script>
