<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery.bxslider.css'));
?>

<style>
    .page_color{
        /*color: #d93600;*/
        color: #ff5300;
    }
    .page_background{
        background-color: #ff5300;
        color: #eee;
    }
</style>
<div class="darkbackground">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext">
                <?php // echo sprintf($this->translate('Map %swhatever%s you like, %swhenever%s you like, %showever%s you like.'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
                <?php echo sprintf($this->translate('An exciting field that %sfuses%s land surveying %stechniques%s with computer %stechnology.%s'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
            </div>
            <a id="go_down" class="skip-icon page_background" title="Skip to content" href="#content"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
    </div>
</div>
<div class="row" id="menu-shrink-mark">
    <ul class="bxslider">
        <li><img src="../img/pic2.jpg" /></li>
        <li><img src="../img/pic3.jpg" /></li>
        <li><img src="../img/pic1.jpg" /></li>
    </ul>
</div>
<div class="row" id="content">
    <div class="col-xs-10 col-xs-offset-1">
<!--        <h2 class="section-title">SERVICES</h2>-->
        <div class="jumbotext3">
            <p><?php echo sprintf($this->translate('Geomatics helps you discover the world.')) ?></p>
        </div>
        <p>Advancements in technology have changed the nature of surveying and mapping. Today, geomatics professionals use an integrated approach to measuring, analyzing and managing spatial data, employing high-tech equipment like Geographic Information Systems (GIS), Global Positioning Systems (GPS), digital photogrammetry, digital total stations, satellite and terrestrial remote sensing to create a detailed but understandable picture of the Earth's natural and manmade features. </p>
        <p>At zeomatics, we use tools such as remote sensing, computer mapping, geographic information systems (GIS), and GPS to analyze information and make meaningful decisions.</p>
    </div>
</div>
<br/>
<br/>
<div class="whitebackground"><br/><br/>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
<!--            <h2 class="section-title">TECHNOLOGY</h2>-->
            <div class="title_font font-54">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/technology/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php echo sprintf($this->translate('An intro to what we do...')) ?>
                    <!--<a class="btn btn-success btn-lg page_background" href="zero/technology">View Technology <span class="glyphicon glyphicon-play"></span></a>-->
                </p>
            </div>
        </div>
    </div>
    <br/>
    <br/>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
<!--            <h2 class="section-title">An intro to what we do</h2>-->
            <div id="cartography" class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/technology/gis-map-rolls_zoomed.jpg');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24 page_background">Cartography / Map Design</p>
                    <p>The practice of creating maps or visual representations of a surface from above it is known as Cartography. Traditionally maps have always on paper, but since the introduction & wide spread use of GIS, cartography has evolved more into digital formats. Most maps today are now generated using map software that falls into one of three main types; GIS, CAD, and specialized map graphic design software.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div id="GIS" class="row service_info">
                <div class="col-lg-5 col-lg-push-7">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/technology/GIS.jpg');?>">
                </div>
                <div class="col-lg-7 col-lg-pull-5">
                    <p class="services_title font-24 page_background">Geographic Information Systems (GIS)</p>
                    <p>GIS have become a rapidly growing field that allows people to solve & model real world situations by incorporating spatial and tabular data. GIS operates on many levels and has become an essential tool for most urban and resource planning and management organizations.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div id="rs" class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/technology/remotesensing.jpg');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24 page_background">Remote Sensing</p>
                    <p>Remote sensing is the science of acquiring information about a surface without physically being in contact with it. The most common example of remote sensing is aerial photography however there are hundreds of  applications ranging from space-borne satellites to under-ground geophysical systems.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div id="LIDAR" class="row service_info">
                <div class="col-lg-5 col-lg-push-7">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/technology/LIDAR.jpg');?>">
                </div>
                <div class="col-lg-7 col-lg-pull-5">
                    <p class="services_title font-24 page_background">LIDAR</p>
                    <p>LIDAR uses high precision GPS with an Inertial Measurement Unit (IMU) to determine accurate surface locations. The resultant measurements consists of geographic locations that can be further processed to produce different spatial data products. We have worked in all aspects of LIDAR, from data acquisition (with both airborne and terrestrial scanners) to processing and product creation.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/technology/bathymetry.jpg');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24 page_background">Bathymetry</p>
                    <p>Bathymetry is the study and mapping of seafloor topography. It involves obtaining measurements of the depth of the ocean and is equivalent to mapping the topography on land.</p>
                    <p>The term “bathymetry” originally referred to the ocean’s depth relative to sea level, although it has come to mean “submarine topography,” or the depths and shapes of underwater terrain.</p>
                    <p>In the same way that topographic maps represent the three-dimensional features (or relief) of overland terrain, bathymetric maps illustrate the land that lies underwater. Variations in sea-floor relief may be depicted by color and contour lines called depth contours or isobaths.</p>
                    <p>Bathymetry is the foundation of the science of hydrography, which measures the physical features of a water body.  Hydrography includes not only bathymetry, but also the shape and features of the shoreline; the characteristics of tides, currents, and waves; and the physical and chemical properties of the water itself.</p>
                    <strong>Such measurements can be made using:</strong>
                    <ul>
                        <li>Multibeam (swath) echosounders</li>
                        <li>Airborne laser measurements (LADS)</li>
                        <li>Derived depths from satellite remote sensing</li>
                        <li>Singlebeam echosounders</li>
                    </ul>
                    <p>Bathymetry is used by engineering companies to site undersea cables, oil rigs and seafloor pipelines. The data may be used also for more specialised activities such as identifying the extent of man-made bio-hazards or for locating material which have escaped onto, or sunk to, the seafloor. Australia's fishing industry also use bathymetric data to identify possible locations for deep sea fishing.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5 col-lg-push-7">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/technology/thermalimaging.jpg');?>">
                </div>
                <div class="col-lg-7 col-lg-pull-5">
                    <p class="services_title font-24 page_background">Thermal Imaging (TABI)</p>
                    <p>Climate change and energy efficiency are high on the political agenda and the Environment Agency has been instrumental in raising awareness of this global issue in the UK.
                    </p><p>
                    In response to this, Environment Agency Geomatics can be commissioned to carry out aerial thermal surveys using a Thermal Airborne Imager™ (TABI), which measures relative heat loss from buildings, landfill sites and industrial sources.
                    </p><p>
                    Using this airborne instrument, both urban and rural areas can be surveyed quickly and cost effectively. Our automated referencing systems give unsurpassed precision, meaning that imagery can be seamlessly matched to buildings located on OS Mastermap™. Statistics of the temperature values within each building polygon are used to assign each address and out-building with an indicative heat loss rating.
                    </p><p>
                    This powerful tool makes it easy to monitor heat loss from commercial and domestic properties and develop targeted energy efficiency plans. The imager can also be used in environmental monitoring to detect industrial thermal discharge into watercourses, oil spillage and heat anomalies on landfill sites.
                    </p><p>
                    Image data can be supplied in a variety of formats to suit the application requirements, with different levels of processing on offer from raw image data to fully analysed data products.
                    </p><p>
                    <strong>Applications:</strong><br/>
                    For both commercial and public sector, this process offers the precision required to better target heat loss.
                    <ul>
                        <li>Local authority energy awareness campaigns</li>
                        <li>Climate change planning</li>
                        <li>Building heat loss measurement</li>
                        <li>Commercial energy loss audits</li>
                        <li>Energy conservation programmes</li>
                        <li>Landfill site surveys</li>
                        <li>Above Ground Pipeline heat loss analysis</li>
                        <li>Industrial thermal discharge analysis</li>
                    </ul>
                    </p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/technology/NASAs-HyspIRI.jpg');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24 page_background">Hyperspectral Imaging</p>
                    <p>Used predominately for environmental monitoring, CASI (Compact Airborne Spectrographic Imager) is a flexible mapping tool capable of multispectral and hyperspectral imaging. This powerful optical imager from ITRES measures reflected light from the visible and near infrared portion of the spectrum (between 400nm and 1000nm), which is split into multiple and discrete image bands.</p>
                    <p>This multispectral imagery is automatically and accurately orthorectified using data from the LIDAR system. The imagery's spatial resolution can be as fine as 50cm and it is map ready so can be used directly in GIS and image processing software.</p>
                    <strong>Applications include:</strong>
                    <ul>
                        <li>Mapping coastal habitats (including change)</li>
                        <li>Land cover classification</li>
                        <li>Flood event monitoring</li>
                        <li>Biomass studies</li>
                        <li>Archaeology</li>
                        <li>Forest management</li>
                        <li>Agricultural crop management</li>
                    </ul>
                    <!--Environment Agency Geomatics has significant skill and expertise in this field and continue to carry out regular work on behalf of the Environment Agency for salt marsh and biomass monitoring, as well as work for other Government Agencies, NGOs and commercial organisations. To learn more about how you can use CASI for environmental monitoring and assessment contact us.-->
                    <p>The ability of multispectral data to quantify parameters such as biomass is a significant advantage over conventional aerial photography.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <br/>
            <br/>
            <br/>
        </div>
    </div>
</div>
<div class="page_background">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext3">
                <?php echo sprintf($this->translate('How might we help you?')) ?>
                <a class="btn btn-default btn-lg" href="zero/contact/">GET IN TOUCH  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //For sliding images in the head slider
    $(document).ready(function(){
      $('.bxslider').bxSlider();
    });
</script>
