<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery.bxslider.css'));
?>

<style>
    .page_color{
        /*color: #d93600;*/
        color: #ff5300;
    }
    .page_background{
        background-color: #ff5300;
        color: #eee;
    }
</style>
<div class="darkbackground">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext">
                <?php echo sprintf($this->translate('Map %swhatever%s you like, %swhenever%s you like, %showever%s you like.'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
            </div>
            <a class="skip-icon page_background" title="Skip to content" href="#content"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
    </div>
</div>
<div class="row" id="menu-shrink-mark">
    <ul class="bxslider">
        <li><img src="../img/pic2.jpg" /></li>
        <li><img src="../img/pic3.jpg" /></li>
        <li><img src="../img/pic1.jpg" /></li>
    </ul>
</div>
<div id="content">
    
</div>
<div class="page_background">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext3">
                <?php echo sprintf($this->translate('How might we help you?')) ?>
                <a class="btn btn-default btn-lg" href="zero/contact/">GET IN TOUCH  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //For sliding images in the head slider
    $(document).ready(function(){
      $('.bxslider').bxSlider();
    });
</script>
