<?php 
$this->headScript()->appendFile($this->basePath('js/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery.bxslider.css'));
?>

<style>
    .page_color{
        /*color: #d93600;*/
        color: #ff5300;
    }
    .page_background{
        background-color: #ff5300;
        color: #eee;
    }
</style>
<div class="darkbackground">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext">
                <?php // echo sprintf($this->translate('Map %swhatever%s you like, %swhenever%s you like, %showever%s you like.'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
                <?php echo sprintf($this->translate('An exciting field that %sfuses%s land surveying %stechniques%s with computer %stechnology.%s'), '<span class="page_color">', '</span>', '<span class="page_color">', '</span>', '<span class="page_color">', '</span>') ?>
            </div>
            <a id="go_down" class="skip-icon page_background" title="Skip to content" href="#content"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
    </div>
</div>
<div class="row" id="menu-shrink-mark">
    <ul class="bxslider">
        <li><img src="../img/pic2.jpg" /></li>
        <li><img src="../img/pic3.jpg" /></li>
        <li><img src="../img/pic1.jpg" /></li>
    </ul>
</div>
<div class="row" id="content">
    <div class="col-xs-10 col-xs-offset-1">
<!--        <h2 class="section-title">SERVICES</h2>-->
        <div class="jumbotext3">
            <p><?php echo sprintf($this->translate('Geomatics helps you discover the world.')) ?></p>
        </div>
        <p>Advancements in technology have changed the nature of surveying and mapping. Today, geomatics professionals use an integrated approach to measuring, analyzing and managing spatial data, employing high-tech equipment like Geographic Information Systems (GIS), Global Positioning Systems (GPS), digital photogrammetry, digital total stations, satellite and terrestrial remote sensing to create a detailed but understandable picture of the Earth's natural and manmade features. </p>
        <p>At zeomatics, we use tools such as remote sensing, computer mapping, geographic information systems (GIS), and GPS to analyze information and make meaningful decisions.</p>
    </div>
</div>
<br/>
<br/>
<div class="whitebackground"><br/><br/>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
<!--            <h2 class="section-title">TECHNOLOGY</h2>-->
            <div class="jumbotext2">
                <!--<p>We help you map and make meaningful connections with your customers. <a class="btn btn-green" href="zero/services/">See how we work  <i class="icon-btn" style="right: 18px;"></i></a></p>-->
                <p>
                <?php echo sprintf($this->translate('An intro to what we do...')) ?>
                    <!--<a class="btn btn-success btn-lg page_background" href="zero/technology">View Technology <span class="glyphicon glyphicon-play"></span></a>-->
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
<!--            <h2 class="section-title">An intro to what we do</h2>-->
            <div class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/cartography.jpg');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24">Cartography / Map Design</p>
                    <p>The practice of creating maps or visual representations of a surface from above it is known as Cartography. Traditionally maps have always on paper, but since the introduction & wide spread use of GIS, cartography has evolved more into digital formats.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5 col-lg-push-7">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/GIS.jpg');?>">
                </div>
                <div class="col-lg-7 col-lg-pull-5">
                    <p class="services_title font-24">Geographic Information Systems (GIS)</p>
                    <p>GIS have become a rapidly growing field that allows people to solve & model real world situations by incorporating spatial and tabular data. GIS operates on many levels and has become an essential tool for most urban and resource planning and management organizations.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/RS.gif');?>">
                </div>
                <div class="col-lg-7">
                    <p class="services_title font-24">Remote Sensing</p>
                    <p>Remote sensing is the science of acquiring information about a surface without physically being in contact with it. The most common example of remote sensing is aerial photography however there are hundreds of  applications ranging from space-borne satellites to under-ground geophysical systems.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <hr/>
            <div class="row service_info">
                <div class="col-lg-5 col-lg-push-7">
                    <img class="img-rounded img-responsive" src="<?php echo $this->basePath('img/services/LIDAR.jpg');?>">
                </div>
                <div class="col-lg-7 col-lg-pull-5">
                    <p class="services_title font-24">LIDAR</p>
                    <p>LIDAR uses high precision GPS with an Inertial Measurement Unit (IMU) to determine accurate surface locations. The resultant measurements consists of geographic locations that can be further processed to produce different spatial data products. We have worked in all aspects of LIDAR, from data acquisition (with both airborne and terrestrial scanners) to processing and product creation.</p>
                    <p><a href="#">Read more >></a></p>
                </div>
            </div>
            <br/>
            <br/>
            <br/>
        </div>
    </div>
</div>
<div class="page_background">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="jumbotext3">
                <?php echo sprintf($this->translate('How might we help you?')) ?>
                <a class="btn btn-default btn-lg" href="zero/contact/">GET IN TOUCH  <span class="glyphicon glyphicon-play"></span></a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //For sliding images in the head slider
    $(document).ready(function(){
      $('.bxslider').bxSlider();
    });
</script>
